//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class arrivalTable
    {
        public string deliveryNo { get; set; }
        public string VIA { get; set; }
        public string WAYBILL { get; set; }
        public Nullable<System.DateTime> dateReceived { get; set; }
        public Nullable<System.DateTime> datePrinted { get; set; }
        public string branchNo { get; set; }
        public string sName { get; set; }
    }
}
