//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        public int indexNo { get; set; }
        public string branchNo { get; set; }
        public string branchName { get; set; }
        public string branchCode { get; set; }
        public string bAddress { get; set; }
        public string bContactNo { get; set; }
    }
}
