//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection
    {
        public int id { get; set; }
        public string Collection_ID { get; set; }
        public string Total_LCP { get; set; }
        public string Payment { get; set; }
        public string Balance { get; set; }
        public string UDI { get; set; }
        public string Total_Rebate { get; set; }
        public string PN { get; set; }
        public string GRS_Monthly { get; set; }
        public string Net_monthly { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public string Notarial_Fee { get; set; }
        public string Delivery_Fee { get; set; }
        public string Other_Pay { get; set; }
        public string Status { get; set; }
        public string terms { get; set; }
        public string paymentType { get; set; }
        public string remarks { get; set; }
        public string monthlyRebate { get; set; }
    }
}
