//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyProfile
    {
        public int indexNo { get; set; }
        public string citiProfileNo { get; set; }
        public string cedula_name { get; set; }
        public string cedula_no { get; set; }
        public Nullable<System.DateTime> cedula_dateissued { get; set; }
        public string place_issued { get; set; }
        public string branchID { get; set; }
    }
}
