//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerTable
    {
        public string ID_Number { get; set; }
        public string last_Name { get; set; }
        public string mid_Name { get; set; }
        public string f_Name { get; set; }
        public string employer { get; set; }
        public string contact { get; set; }
        public string co_Maker { get; set; }
        public string address { get; set; }
        public string co_MakerAddress { get; set; }
        public string civil_status { get; set; }
        public string employerAddress { get; set; }
        public string fullName { get; set; }
    }
}
