//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DR_details
    {
        public int id { get; set; }
        public string DR_Details_ID { get; set; }
        public string LCP { get; set; }
        public string stockNo { get; set; }
        public string AccountNo { get; set; }
        public string qnty { get; set; }
        public string remarks { get; set; }
        public string down_payment { get; set; }
        public string or_number { get; set; }
        public string paymentType { get; set; }
        public string description { get; set; }
        public string pStatus { get; set; }
        public string cash { get; set; }
        public string orAmt { get; set; }
        public string model { get; set; }
        public string serialNo { get; set; }
        public string brand { get; set; }
        public string PN { get; set; }
        public string BalanceAF { get; set; }
        public string termsDR { get; set; }
    }
}
