//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class freeProduct
    {
        public int indexNo { get; set; }
        public string FstockNo { get; set; }
        public string stockNo { get; set; }
        public string attachedStockNo { get; set; }
    }
}
