//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OF_Table
    {
        public string OFID { get; set; }
        public string FeeType { get; set; }
        public string ORNumber { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> trans_Id { get; set; }
        public string payments { get; set; }
        public string paymentType { get; set; }
        public string cash_amt { get; set; }
        public string cheque_amt { get; set; }
    }
}
