//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class poDetail
    {
        public int indexNo { get; set; }
        public string poDetails_ID { get; set; }
        public string model { get; set; }
        public string orderedQTY { get; set; }
        public string freeQTY { get; set; }
        public string cost { get; set; }
        public string discount { get; set; }
        public string totalCost { get; set; }
        public string poID { get; set; }
        public string brand { get; set; }
        public string totalQty { get; set; }
        public string status { get; set; }
        public string remainingQTY { get; set; }
        public string holderQTY { get; set; }
    }
}
