//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class productList
    {
        public string product_ID { get; set; }
        public string brandID { get; set; }
        public string modelID { get; set; }
        public string sup_IDno { get; set; }
        public string price { get; set; }
    }
}
