//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string stockNo { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public string serialNo { get; set; }
        public string status { get; set; }
        public string poDetails_ID { get; set; }
        public string prodStatus { get; set; }
        public string deliveryNo { get; set; }
        public string loc_From { get; set; }
        public string loc_To { get; set; }
        public Nullable<System.DateTime> date_Received { get; set; }
        public string st_ID { get; set; }
        public string price { get; set; }
        public string branchNo { get; set; }
    }
}
