//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class st_requisitionTable
    {
        public string st_ID { get; set; }
        public Nullable<System.DateTime> date_Transaction { get; set; }
        public string transfer_location { get; set; }
        public string gatePassNo { get; set; }
        public string receivedBy { get; set; }
        public string releasedBy { get; set; }
        public string from_location { get; set; }
    }
}
