//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citiAppSystem.Modules.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferTable
    {
        public string transfer_ID { get; set; }
        public string stockNo { get; set; }
        public Nullable<System.DateTime> trans_Date { get; set; }
        public string transferLocation { get; set; }
        public string qnty { get; set; }
        public string st_ID { get; set; }
    }
}
